services:
  db:
    image: postgres:15-alpine
    container_name: uniform-system-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: uniform_db
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db-data:
